---
version: "2.0"

services:
  web:
    image: user994455/ubuntu-base:0.2
    env:
      - sshport=22322
      - pubkey=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCoz8I2ZC/e6D6Xs/jtoWe7QQJdGQiErXZSk3AsRn6PHyrnOxy7wu3Rgb1v3NrTXLKnFsJwgWWYtPh4piEzWLYG0VJFI7LRk8OdzYPyfwE2v9bsSt0U3zw6z7Gq3er9UXCII8QhgPzxSgYcqaSIHz60TDZV0yWPZuMwHUxA4wssaWAAkRbdrP5abXgdjhTw4eqQuvgQQ6nJMcTGvYRikCoSn3kd+U4j55Qht1uD9bms1h2pIZbaJ7/mbuFYNO5AOSwrrv4YkWfqO8MagGaBiSsIsa6FObrkDg6QZFrqWjWo+0oz33THxZBOlxuc4vaD/vk0EpzHmSoq3BX0fi0lRzZQbG2JEtZ5IxU0u3TIWwIosbSk3shSWFzK1CIa5bBTD6nHwaHyzoNfFZ7pttcmrObxproMqvu39EZLgXhWbethgOCYuMqR7SdNdbAKLySnDThYRCD2iptQamGdQ4vhI/N8H9JlUNMnjsPN8T8XKYLmOxE3O4XTxGzkiSlBNnHOjjk= Admin
    expose:
      - port: 22322
        as: 22322
        to:
          - global: true
      - port: 8080
        as: 80
        to:
          - global: true
      - port: 26657
        to:
          - global: true
      - port: 26656
        to:
          - global: true
      - port: 1317
        to:
          - global: true
      - port: 9090
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          size: 128Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 100

deployment:
  web:
    dcloud:
      profile: web
      count: 1
