---
version: "2.0"

services:
  web:
    image: user994455/ubuntu-base:0.2
    env:
      - sshport=22
      - pubkey=<YOUR_SSH_PUBLIC_KEY-NO_QUOTES>
    expose:
      - port: 22
        as: 22
        to:
          - global: true
      - port: 8080
        as: 80
        to:
          - global: true
      - port: 26657
        to:
          - global: true
      - port: 26656
        to:
          - global: true
      - port: 1317
        to:
          - global: true
      - port: 9090
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          size: 128Gi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web:
          denom: uakt
          amount: 100

deployment:
  web:
    dcloud:
      profile: web
      count: 1
